services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-assistente-institucional
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data_assistente:/qdrant/storage

  postgres:
    image: postgres:16
    container_name: postgres-assistente-institucional
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data_assistente:/var/lib/postgresql/data 

  
  api:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: assistente-institucional-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      QDRANT_URL: http://qdrant:6333

    depends_on:
      - postgres
      - qdrant

volumes:
  qdrant_data_assistente:
  postgres_data_assistente: